version: "3"
services:
  # backend:
  #   container_name: "backend"
  #   build: ./backend/
  #   ports:
  #     - "3001:3001"
  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "admin" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  # frontend:
  #   container_name: "frontend"
  #   build: ./frontend/
  #   ports:
  #     - "3000:3000"
